import { Data, IProductInput, IUserInput } from "@/types";
import { toSlug } from "./utils";
import bcrypt from "bcryptjs";
import { i18n } from "@/i18n-config";

// User data
const users: IUserInput[] = [
  {
    name: "John",
    email: "admin@example.com",
    password: bcrypt.hashSync("123456NN@#s", 5),
    role: "admin",
    address: {
      fullName: "John Doe",
      street: "111 Main St",
      city: "New York",
      province: "NY",
      postalCode: "10001",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "Stripe",
    emailVerified: false,
  },
  {
    name: "Jane",
    email: "jane@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "manager",
    address: {
      fullName: "Jane Harris",
      street: "222 Main St",
      city: "New York",
      province: "NY",
      postalCode: "1002",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "Cash On Delivery",
    emailVerified: false,
  },
  {
    name: "Jack",
    email: "jack@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "seller",
    address: {
      fullName: "Jack Ryan",
      street: "333 Main St",
      city: "New York",
      province: "NY",
      postalCode: "1003",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "PayPal",
    emailVerified: false,
  },
  {
    name: "Sarah",
    email: "sarah@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "user",
    address: {
      fullName: "Sarah Smith",
      street: "444 Main St",
      city: "New York",
      province: "NY",
      postalCode: "1005",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "Cash On Delivery",
    emailVerified: false,
  },
  {
    name: "Michael",
    email: "michael@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "user",
    address: {
      fullName: "John Alexander",
      street: "555 Main St",
      city: "New York",
      province: "NY",
      postalCode: "1006",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "PayPal",
    emailVerified: false,
  },
  {
    name: "Emily",
    email: "emily@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "user",
    address: {
      fullName: "Emily Johnson",
      street: "666 Main St",
      city: "New York",
      province: "NY",
      postalCode: "10001",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "Stripe",
    emailVerified: false,
  },
  {
    name: "Alice",
    email: "alice@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "user",
    address: {
      fullName: "Alice Cooper",
      street: "777 Main St",
      city: "New York",
      province: "NY",
      postalCode: "10007",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "Cash On Delivery",
    emailVerified: false,
  },
  {
    name: "Tom",
    email: "tom@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "user",
    address: {
      fullName: "Tom Hanks",
      street: "888 Main St",
      city: "New York",
      province: "NY",
      postalCode: "10008",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "Stripe",
    emailVerified: false,
  },
  {
    name: "Linda",
    email: "linda@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "user",
    address: {
      fullName: "Linda Holmes",
      street: "999 Main St",
      city: "New York",
      province: "NY",
      postalCode: "10009",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "PayPal",
    emailVerified: false,
  },
  {
    name: "George",
    email: "george@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "user",
    address: {
      fullName: "George Smith",
      street: "101 First Ave",
      city: "New York",
      province: "NY",
      postalCode: "10010",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "Stripe",
    emailVerified: false,
  },
  {
    name: "Jessica",
    email: "jessica@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "user",
    address: {
      fullName: "Jessica Brown",
      street: "102 First Ave",
      city: "New York",
      province: "NY",
      postalCode: "10011",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "Cash On Delivery",
    emailVerified: false,
  },
  {
    name: "Chris",
    email: "chris@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "user",
    address: {
      fullName: "Chris Evans",
      street: "103 First Ave",
      city: "New York",
      province: "NY",
      postalCode: "10012",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "PayPal",
    emailVerified: false,
  },
  {
    name: "Samantha",
    email: "samantha@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "user",
    address: {
      fullName: "Samantha Wilson",
      street: "104 First Ave",
      city: "New York",
      province: "NY",
      postalCode: "10013",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "Stripe",
    emailVerified: false,
  },
  {
    name: "David",
    email: "david@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "user",
    address: {
      fullName: "David Lee",
      street: "105 First Ave",
      city: "New York",
      province: "NY",
      postalCode: "10014",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "Cash On Delivery",
    emailVerified: false,
  },
  {
    name: "Anna",
    email: "anna@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "user",
    address: {
      fullName: "Anna Smith",
      street: "106 First Ave",
      city: "New York",
      province: "NY",
      postalCode: "10015",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "PayPal",
    emailVerified: false,
  },
];
// Product data
const products: IProductInput[] = [
  // iPhone Series
  {
    name: "Apple iPhone 16 Pro Max",
    slug: toSlug("Apple iPhone 16 Pro Max"),
    sku: "APPLE-SMARTPHONES-001",
    category: "Smartphones",
    images: ["/images/iPhone16pro max.png"],
    tags: ["new-arrival", "bestseller"],
    isPublished: true,
    price: 1299,
    listPrice: 1399,
    brand: "Apple",
    avgRating: 4.9,
    numReviews: 145,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 5 },
      { rating: 4, count: 22 },
      { rating: 5, count: 115 },
    ],
    numSales: 420,
    countInStock: 35,
    description: "Latest iPhone with A18 Pro chip, titanium design, advanced camera system with 5x telephoto zoom, and Action Button.",
    sizes: ["256GB", "512GB", "1TB"],
    colors: ["Natural Titanium", "Blue Titanium", "White Titanium", "Black Titanium"],
    reviews: [],
  },
  {
    name: "Apple iPhone 16",
    slug: toSlug("Apple iPhone 16"),
    sku: "APPLE-SMARTPHONES-002",
    category: "Smartphones",
    images: ["/images/iPhone16.png"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 899,
    listPrice: 999,
    brand: "Apple",
    avgRating: 4.7,
    numReviews: 98,
    ratingDistribution: [
      { rating: 1, count: 2 },
      { rating: 2, count: 3 },
      { rating: 3, count: 8 },
      { rating: 4, count: 25 },
      { rating: 5, count: 60 },
    ],
    numSales: 280,
    countInStock: 45,
    description: "iPhone 16 with A18 chip, Camera Control, and enhanced battery life for all-day performance.",
    sizes: ["128GB", "256GB", "512GB"],
    colors: ["Black", "White", "Pink", "Teal", "Ultramarine"],
    reviews: [],
  },
  {
    name: "Apple iPhone 15 Pro Max",
    slug: toSlug("Apple iPhone 15 Pro Max"),
    sku: "APPLE-SMARTPHONES-003",
    category: "Smartphones",
    images: ["/images/iPhone15Pro Max.png"],
    tags: ["featured"],
    isPublished: true,
    price: 1199,
    listPrice: 1299,
    brand: "Apple",
    avgRating: 4.8,
    numReviews: 220,
    ratingDistribution: [
      { rating: 1, count: 2 },
      { rating: 2, count: 3 },
      { rating: 3, count: 10 },
      { rating: 4, count: 35 },
      { rating: 5, count: 170 },
    ],
    numSales: 380,
    countInStock: 28,
    description: "iPhone 15 Pro Max with A17 Pro chip, titanium build, and professional camera system.",
    sizes: ["256GB", "512GB", "1TB"],
    colors: ["Natural Titanium", "Blue Titanium", "White Titanium", "Black Titanium"],
    reviews: [],
  },
  {
    name: "Apple iPhone 15",
    slug: toSlug("Apple iPhone 15"),
    sku: "APPLE-SMARTPHONES-004",
    category: "Smartphones",
    images: ["/images/iPhone15.png"],
    tags: ["bestseller"],
    isPublished: true,
    price: 799,
    listPrice: 899,
    brand: "Apple",
    avgRating: 4.6,
    numReviews: 156,
    ratingDistribution: [
      { rating: 1, count: 3 },
      { rating: 2, count: 5 },
      { rating: 3, count: 12 },
      { rating: 4, count: 40 },
      { rating: 5, count: 96 },
    ],
    numSales: 320,
    countInStock: 52,
    description: "iPhone 15 with A16 Bionic chip, USB-C, and Dynamic Island for an enhanced user experience.",
    sizes: ["128GB", "256GB", "512GB"],
    colors: ["Pink", "Yellow", "Green", "Blue", "Black"],
    reviews: [],
  },
  {
    name: "Samsung Galaxy S25 Ultra",
    slug: toSlug("Samsung Galaxy S25 Ultra"),
    sku: "SAMSUNG-SMARTPHONES-001",
    category: "Smartphones",
    images: ["/images/GalaxyS25Ultra.png"],
    tags: ["new-arrival", "featured"],
    isPublished: true,
    price: 1299,
    listPrice: 1399,
    brand: "Samsung",
    avgRating: 4.8,
    numReviews: 89,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 6 },
      { rating: 4, count: 20 },
      { rating: 5, count: 60 },
    ],
    numSales: 195,
    countInStock: 32,
    description: "Latest Samsung flagship with S Pen, 200MP camera, Snapdragon 8 Gen 4, and AI features.",
    sizes: ["256GB", "512GB", "1TB"],
    colors: ["Titanium Black", "Titanium Gray", "Titanium Blue", "Titanium Silver"],
    reviews: [],
  },
  {
    name: "Samsung Galaxy S25 Plus",
    slug: toSlug("Samsung Galaxy S25 Plus"),
    sku: "SAMSUNG-SMARTPHONES-002",
    category: "Smartphones",
    images: ["/images/GalaxyS25plus.png"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 999,
    listPrice: 1099,
    brand: "Samsung",
    avgRating: 4.7,
    numReviews: 76,
    ratingDistribution: [
      { rating: 1, count: 2 },
      { rating: 2, count: 3 },
      { rating: 3, count: 8 },
      { rating: 4, count: 23 },
      { rating: 5, count: 40 },
    ],
    numSales: 145,
    countInStock: 28,
    description: "Samsung Galaxy S25+ with enhanced camera system, larger display, and premium build quality.",
    sizes: ["256GB", "512GB"],
    colors: ["Navy", "Silver", "Mint", "Coral"],
    reviews: [],
  },
  {
    name: "Samsung Galaxy S25",
    slug: toSlug("Samsung Galaxy S25"),
    sku: "SAMSUNG-SMARTPHONES-003",
    category: "Smartphones",
    images: ["/images/GalaxyS25.png"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 799,
    listPrice: 899,
    brand: "Samsung",
    avgRating: 4.6,
    numReviews: 92,
    ratingDistribution: [
      { rating: 1, count: 3 },
      { rating: 2, count: 4 },
      { rating: 3, count: 10 },
      { rating: 4, count: 25 },
      { rating: 5, count: 50 },
    ],
    numSales: 168,
    countInStock: 42,
    description: "Compact Samsung Galaxy S25 with flagship performance, excellent cameras, and sleek design.",
    sizes: ["128GB", "256GB", "512GB"],
    colors: ["Phantom Black", "Cream", "Violet", "Green"],
    reviews: [],
  },
  {
    name: "Samsung Galaxy Z Fold6",
    slug: toSlug("Samsung Galaxy Z Fold6"),
    sku: "SAMSUNG-SMARTPHONES-004",
    category: "Smartphones",
    images: ["/images/GalaxyZFold6.png"],
    tags: ["featured", "foldable"],
    isPublished: true,
    price: 1899,
    listPrice: 1999,
    brand: "Samsung",
    avgRating: 4.5,
    numReviews: 67,
    ratingDistribution: [
      { rating: 1, count: 3 },
      { rating: 2, count: 4 },
      { rating: 3, count: 8 },
      { rating: 4, count: 22 },
      { rating: 5, count: 30 },
    ],
    numSales: 89,
    countInStock: 18,
    description: "Revolutionary foldable smartphone with 7.6-inch main display, S Pen support, and multitasking capabilities.",
    sizes: ["256GB", "512GB", "1TB"],
    colors: ["Silver Shadow", "Pink", "Navy", "Crafted Black"],
    reviews: [],
  },
  {
    name: "Samsung Galaxy Z Flip6",
    slug: toSlug("Samsung Galaxy Z Flip6"),
    sku: "SAMSUNG-SMARTPHONES-005",
    category: "Smartphones",
    images: ["/images/GalaxyZFlip6.png"],
    tags: ["featured", "foldable"],
    isPublished: true,
    price: 1099,
    listPrice: 1199,
    brand: "Samsung",
    avgRating: 4.4,
    numReviews: 84,
    ratingDistribution: [
      { rating: 1, count: 4 },
      { rating: 2, count: 5 },
      { rating: 3, count: 12 },
      { rating: 4, count: 28 },
      { rating: 5, count: 35 },
    ],
    numSales: 126,
    countInStock: 25,
    description: "Compact foldable phone with improved hinge, enhanced cameras, and all-day battery life.",
    sizes: ["256GB", "512GB"],
    colors: ["Silver Shadow", "Yellow", "Mint", "Blue", "Peach"],
    reviews: [],
  },
  {
    name: "Samsung Galaxy S24 FE",
    slug: toSlug("Samsung Galaxy S24 FE"),
    sku: "SAMSUNG-SMARTPHONES-006",
    category: "Smartphones",
    images: ["/images/GalaxyS24FE.png"],
    tags: ["bestseller"],
    isPublished: true,
    price: 649,
    listPrice: 749,
    brand: "Samsung",
    avgRating: 4.5,
    numReviews: 134,
    ratingDistribution: [
      { rating: 1, count: 4 },
      { rating: 2, count: 6 },
      { rating: 3, count: 15 },
      { rating: 4, count: 42 },
      { rating: 5, count: 67 },
    ],
    numSales: 245,
    countInStock: 58,
    description: "Fan Edition Galaxy with flagship features, excellent value, and long-term software support.",
    sizes: ["128GB", "256GB"],
    colors: ["Graphite", "Blue", "Mint", "Yellow"],
    reviews: [],
  },
  {
    name: "Oppo Find X8 Pro",
    slug: toSlug("Oppo Find X8 Pro"),
    sku: "OPPO-SMARTPHONES-001",
    category: "Smartphones",
    images: ["/images/OppoFindX8Pro.png"],
    tags: ["new-arrival", "camera"],
    isPublished: true,
    price: 1199,
    listPrice: 1299,
    brand: "Oppo",
    avgRating: 4.6,
    numReviews: 56,
    ratingDistribution: [
      { rating: 1, count: 2 },
      { rating: 2, count: 3 },
      { rating: 3, count: 6 },
      { rating: 4, count: 18 },
      { rating: 5, count: 27 },
    ],
    numSales: 78,
    countInStock: 22,
    description: "Premium Oppo flagship with Hasselblad cameras, MediaTek Dimensity 9400, and fast charging.",
    sizes: ["256GB", "512GB"],
    colors: ["Space Black", "Pearl White", "Desert Silver"],
    reviews: [],
  },
  {
    name: "Oppo Find X8",
    slug: toSlug("Oppo Find X8"),
    sku: "OPPO-SMARTPHONES-002",
    category: "Smartphones",
    images: ["/images/OppoFindX8.png"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 899,
    listPrice: 999,
    brand: "Oppo",
    avgRating: 4.4,
    numReviews: 43,
    ratingDistribution: [
      { rating: 1, count: 2 },
      { rating: 2, count: 4 },
      { rating: 3, count: 8 },
      { rating: 4, count: 15 },
      { rating: 5, count: 14 },
    ],
    numSales: 65,
    countInStock: 35,
    description: "Oppo Find X8 with advanced AI photography, sleek design, and flagship performance.",
    sizes: ["128GB", "256GB", "512GB"],
    colors: ["Star Grey", "Shell Pink", "Blue"],
    reviews: [],
  },
  {
    name: "Oppo Reno13 Pro 5G",
    slug: toSlug("Oppo Reno13 Pro 5G"),
    sku: "OPPO-SMARTPHONES-003",
    category: "Smartphones",
    images: ["/images/OppoReno13 Pro5G.png"],
    tags: ["camera", "5g"],
    isPublished: true,
    price: 649,
    listPrice: 749,
    brand: "Oppo",
    avgRating: 4.3,
    numReviews: 67,
    ratingDistribution: [
      { rating: 1, count: 3 },
      { rating: 2, count: 5 },
      { rating: 3, count: 12 },
      { rating: 4, count: 22 },
      { rating: 5, count: 25 },
    ],
    numSales: 98,
    countInStock: 41,
    description: "Mid-range Oppo with excellent portrait photography, 5G connectivity, and premium design.",
    sizes: ["128GB", "256GB"],
    colors: ["Midnight Black", "Butterfly Purple", "Gold"],
    reviews: [],
  },
  // MacBook Series
  {
    name: "MacBook Pro 16-inch M3 Max",
    slug: toSlug("MacBook Pro 16-inch M3 Max"),
    sku: "APPLE-LAPTOPS-001",
    category: "Laptops",
    images: ["/images/macbook1.png"],
    tags: ["new-arrival", "professional"],
    isPublished: true,
    price: 3499,
    listPrice: 3699,
    brand: "Apple",
    avgRating: 4.9,
    numReviews: 87,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 1 },
      { rating: 3, count: 3 },
      { rating: 4, count: 12 },
      { rating: 5, count: 70 },
    ],
    numSales: 156,
    countInStock: 18,
    description: "Ultimate MacBook Pro with M3 Max chip, 16-inch Liquid Retina XDR display, and professional performance.",
    sizes: ["512GB", "1TB", "2TB", "4TB"],
    colors: ["Space Black", "Silver"],
    reviews: [],
  },
  {
    name: "MacBook Pro 14-inch M3 Pro",
    slug: toSlug("MacBook Pro 14-inch M3 Pro"),
    sku: "APPLE-LAPTOPS-002",
    category: "Laptops",
    images: ["/images/macbook2.png"],
    tags: ["professional"],
    isPublished: true,
    price: 2499,
    listPrice: 2699,
    brand: "Apple",
    avgRating: 4.8,
    numReviews: 124,
    ratingDistribution: [
      { rating: 1, count: 2 },
      { rating: 2, count: 2 },
      { rating: 3, count: 6 },
      { rating: 4, count: 24 },
      { rating: 5, count: 90 },
    ],
    numSales: 234,
    countInStock: 28,
    description: "Powerful MacBook Pro with M3 Pro chip, 14-inch Liquid Retina XDR display, and advanced connectivity.",
    sizes: ["512GB", "1TB", "2TB"],
    colors: ["Space Black", "Silver"],
    reviews: [],
  },
  {
    name: "MacBook Air 15-inch M3",
    slug: toSlug("MacBook Air 15-inch M3"),
    sku: "APPLE-LAPTOPS-003",
    category: "Laptops",
    images: ["/images/macbook3.png"],
    tags: ["bestseller"],
    isPublished: true,
    price: 1499,
    listPrice: 1599,
    brand: "Apple",
    avgRating: 4.7,
    numReviews: 198,
    ratingDistribution: [
      { rating: 1, count: 3 },
      { rating: 2, count: 4 },
      { rating: 3, count: 12 },
      { rating: 4, count: 45 },
      { rating: 5, count: 134 },
    ],
    numSales: 387,
    countInStock: 45,
    description: "Large-screen MacBook Air with M3 chip, 15-inch Liquid Retina display, and all-day battery life.",
    sizes: ["256GB", "512GB", "1TB", "2TB"],
    colors: ["Midnight", "Starlight", "Silver", "Space Gray"],
    reviews: [],
  },
  {
    name: "MacBook Air 13-inch M3",
    slug: toSlug("MacBook Air 13-inch M3"),
    sku: "APPLE-LAPTOPS-004",
    category: "Laptops",
    images: ["/images/macbook4.png"],
    tags: ["bestseller"],
    isPublished: true,
    price: 1199,
    listPrice: 1299,
    brand: "Apple",
    avgRating: 4.6,
    numReviews: 267,
    ratingDistribution: [
      { rating: 1, count: 4 },
      { rating: 2, count: 6 },
      { rating: 3, count: 18 },
      { rating: 4, count: 62 },
      { rating: 5, count: 177 },
    ],
    numSales: 456,
    countInStock: 62,
    description: "Compact MacBook Air with M3 chip, 13-inch Liquid Retina display, and incredible portability.",
    sizes: ["256GB", "512GB", "1TB", "2TB"],
    colors: ["Midnight", "Starlight", "Silver", "Space Gray"],
    reviews: [],
  },
  // iPad Series
  {
    name: "iPad Pro 12.9-inch M4",
    slug: toSlug("iPad Pro 12.9-inch M4"),
    sku: "APPLE-TABLETS-001",
    category: "Tablets",
    images: ["/images/ipad1.png"],
    tags: ["new-arrival", "professional"],
    isPublished: true,
    price: 1299,
    listPrice: 1399,
    brand: "Apple",
    avgRating: 4.8,
    numReviews: 156,
    ratingDistribution: [
      { rating: 1, count: 2 },
      { rating: 2, count: 3 },
      { rating: 3, count: 8 },
      { rating: 4, count: 28 },
      { rating: 5, count: 115 },
    ],
    numSales: 298,
    countInStock: 34,
    description: "Most advanced iPad Pro with M4 chip, Ultra Retina XDR display, and Apple Pencil Pro support.",
    sizes: ["256GB", "512GB", "1TB", "2TB"],
    colors: ["Silver", "Space Black"],
    reviews: [],
  },
  {
    name: "iPad Pro 11-inch M4",
    slug: toSlug("iPad Pro 11-inch M4"),
    sku: "APPLE-TABLETS-002",
    category: "Tablets",
    images: ["/images/ipad2.png"],
    tags: ["new-arrival", "professional"],
    isPublished: true,
    price: 999,
    listPrice: 1099,
    brand: "Apple",
    avgRating: 4.7,
    numReviews: 189,
    ratingDistribution: [
      { rating: 1, count: 3 },
      { rating: 2, count: 4 },
      { rating: 3, count: 12 },
      { rating: 4, count: 38 },
      { rating: 5, count: 132 },
    ],
    numSales: 345,
    countInStock: 42,
    description: "Compact iPad Pro with M4 chip, Liquid Retina display, and professional capabilities.",
    sizes: ["128GB", "256GB", "512GB", "1TB", "2TB"],
    colors: ["Silver", "Space Black"],
    reviews: [],
  },
  {
    name: "iPad Air 11-inch M2",
    slug: toSlug("iPad Air 11-inch M2"),
    sku: "APPLE-TABLETS-003",
    category: "Tablets",
    images: ["/images/ipad3.png"],
    tags: ["bestseller"],
    isPublished: true,
    price: 699,
    listPrice: 799,
    brand: "Apple",
    avgRating: 4.6,
    numReviews: 234,
    ratingDistribution: [
      { rating: 1, count: 4 },
      { rating: 2, count: 6 },
      { rating: 3, count: 18 },
      { rating: 4, count: 56 },
      { rating: 5, count: 150 },
    ],
    numSales: 423,
    countInStock: 58,
    description: "Versatile iPad Air with M2 chip, 11-inch Liquid Retina display, and Apple Pencil support.",
    sizes: ["128GB", "256GB", "512GB", "1TB"],
    colors: ["Blue", "Purple", "Starlight", "Space Gray"],
    reviews: [],
  }
];
// Review data
const reviews = [
  {
    rating: 1,
    title: "Poor quality",
    comment:
      "Very disappointed. The item broke after just a few uses. Not worth the money.",
  },
  {
    rating: 2,
    title: "Disappointed",
    comment:
      "Not as expected. The material feels cheap, and it didn't fit well. Wouldn't buy again.",
  },
  {
    rating: 2,
    title: "Needs improvement",
    comment:
      "It looks nice but doesn't perform as expected. Wouldn't recommend without upgrades.",
  },
  {
    rating: 3,
    title: "not bad",
    comment:
      "This product is decent, the quality is good but it could use some improvements in the details.",
  },
  {
    rating: 3,
    title: "Okay, not great",
    comment:
      "It works, but not as well as I hoped. Quality is average and lacks some finishing.",
  },
  {
    rating: 3,
    title: "Good product",
    comment:
      "This product is amazing, I love it! The quality is top notch, the material is comfortable and breathable.",
  },
  {
    rating: 4,
    title: "Pretty good",
    comment:
      "Solid product! Great value for the price, but there's room for minor improvements.",
  },
  {
    rating: 4,
    title: "Very satisfied",
    comment:
      "Good product! High quality and worth the price. Would consider buying again.",
  },
  {
    rating: 4,
    title: "Absolutely love it!",
    comment:
      "Perfect in every way! The quality, design, and comfort exceeded all my expectations.",
  },
  {
    rating: 4,
    title: "Exceeded expectations!",
    comment:
      "Fantastic product! High quality, feels durable, and performs well. Highly recommend!",
  },
  {
    rating: 5,
    title: "Perfect purchase!",
    comment:
      "Couldn't be happier with this product. The quality is excellent, and it works flawlessly!",
  },
  {
    rating: 5,
    title: "Highly recommend",
    comment:
      "Amazing product! Worth every penny, great design, and feels premium. I'm very satisfied.",
  },
  {
    rating: 5,
    title: "Just what I needed",
    comment:
      "Exactly as described! Quality exceeded my expectations, and it arrived quickly.",
  },
  {
    rating: 5,
    title: "Excellent choice!",
    comment:
      "This product is outstanding! Everything about it feels top-notch, from material to functionality.",
  },
  {
    rating: 5,
    title: "Couldn't ask for more!",
    comment:
      "Love this product! It's durable, stylish, and works great. Would buy again without hesitation.",
  },
];
// Web page data
const data: Data = {
  users,
  products,
  reviews,
  webPages: [
    {
      title: "About Us",
      slug: "about-us",
      content: `Welcome to ElectroHub, your trusted destination for the latest electronics and cutting-edge technology. Our journey began with a mission to bring you the best electronic devices at competitive prices, all in one convenient platform.

At ElectroHub, we specialize in premium smartphones, laptops, tablets, and accessories from top brands like Apple, Samsung, and Oppo. We prioritize customer satisfaction and innovation, working tirelessly to curate the latest devices and exclusive deals, ensuring there's something for every tech enthusiast.

As we continue to grow, our commitment to quality and service remains unwavering. Thank you for choosing ElectroHub—we look forward to being a part of your tech journey and delivering cutting-edge technology every step of the way.`,
      isPublished: true,
    },
    {
      title: "Contact Us",
      slug: "contact-us",
      content: `We're here to help! If you have any questions, concerns, or feedback about our electronic products, please don't hesitate to reach out to us. Our tech-savvy team is ready to assist you and ensure you have the best shopping experience.

**Customer Support**
For inquiries about orders, products, or account-related issues, contact our customer support team:
- **Email:** support@electrohub.com
- **Phone:** +1 (123) 456-7890
- **Live Chat:** Available on our website from 9 AM to 6 PM (Monday to Friday).

**Head Office**
For corporate or business-related inquiries, reach out to our headquarters:
- **Address:** 1234 Tech Street, Suite 567, Silicon Valley, CA 12345
- **Phone:** +1 (987) 654-3210

We look forward to assisting you! Your satisfaction is our priority.`,
      isPublished: true,
    },
    {
      title: "Help",
      slug: "help",
      content: `Welcome to our Help Center! We're here to assist you with any questions or concerns you may have while shopping for electronics with us. Whether you need help with orders, account management, or product inquiries, this page provides all the information you need.

**Placing and Managing Orders**
Placing an order is simple and secure. Browse our electronic categories, add items to your cart, and proceed to checkout. Once your order is placed, you can track its status through your account under the "My Orders" section. If you need to modify or cancel your order, please contact us as soon as possible.

**Shipping and Returns**
We offer various shipping options for your electronic purchases, including standard and express delivery. For detailed shipping costs and delivery timelines, visit our Shipping Policy page. If you're not satisfied with your purchase, our hassle-free return process allows you to initiate a return within the specified timeframe.

**Account and Support**
Managing your account is easy. Log in to update your personal information, payment methods, and saved addresses. If you encounter any issues or need further assistance, our customer support team is available via email, live chat, or phone.`,
      isPublished: true,
    },
    {
      title: "Privacy Policy",
      slug: "privacy-policy",
      content: `We value your privacy and are committed to protecting your personal information. This Privacy Notice explains how we collect, use, and share your data when you interact with our electronics store services.

We collect data such as your name, email address, and payment details to provide you with tailored services and improve your shopping experience. This information may also be used for marketing purposes, but only with your consent. Additionally, we may share your data with trusted third-party providers to facilitate transactions or deliver products.

Your data is safeguarded through robust security measures to prevent unauthorized access. However, you have the right to access, correct, or delete your personal information at any time. For inquiries or concerns regarding your privacy, please contact our support team.`,
      isPublished: true,
    },
    {
      title: "Conditions of Use",
      slug: "conditions-of-use",
      content: `Welcome to ElectroHub. By accessing or using our website, you agree to comply with and be bound by the following terms and conditions. These terms govern your use of our platform, including browsing, purchasing electronic products, and interacting with any content or services provided.

We strive to ensure all product descriptions, pricing, and availability information on our website are accurate. However, errors may occur, and we reserve the right to correct them without prior notice. All purchases are subject to our return and refund policy. By using our site, you acknowledge that your personal information will be processed according to our privacy policy.

Please review these terms carefully before proceeding with any transactions. You must be at least 18 years old or have the consent of a parent or guardian to use this website.`,
      isPublished: true,
    },
    {
      title: "Customer Service",
      slug: "customer-service",
      content: `At ElectroHub, our customer service team is here to ensure you have the best electronics shopping experience. Whether you need assistance with orders, product details, or returns, we are committed to providing prompt and helpful support.

If you have questions or concerns, please reach out to us through our multiple contact options:
- **Email:** support@electrohub.com
- **Phone:** +1 (123) 456-7890
- **Live Chat:** Available on our website for instant assistance

We also provide helpful resources such as order tracking, product guides, and FAQs to assist you with common inquiries. Your satisfaction is our priority, and we're here to resolve any issues quickly and efficiently.`,
      isPublished: true,
    },
    {
      title: "Returns Policy",
      slug: "returns-policy",
      content: "Returns Policy Content",
      isPublished: true,
    },
    {
      title: "Careers",
      slug: "careers",
      content: "careers Content",
      isPublished: true,
    },
    {
      title: "Blog",
      slug: "blog",
      content: "Blog Content",
      isPublished: true,
    },
    {
      title: "Sell Products",
      slug: "sell",
      content: `Sell Products Content`,
      isPublished: true,
    },
    {
      title: "Become Affiliate",
      slug: "become-affiliate",
      content: "Become Affiliate Content",
      isPublished: true,
    },
    {
      title: "Advertise Your Products",
      slug: "advertise",
      content: "Advertise Your Products",
      isPublished: true,
    },
    {
      title: "Shipping Rates & Policies",
      slug: "shipping",
      content: "Shipping Rates & Policies",
      isPublished: true,
    },
  ],
  headerMenus: [
    {
      name: "Today's Deal",
      href: "/search?tag=todays-deal",
    },
    {
      name: "New Arrivals",
      href: "/search?tag=new-arrival",
    },
    {
      name: "Featured Products",
      href: "/search?tag=featured",
    },
    {
      name: "Best Sellers",
      href: "/search?tag=bestseller",
    },
    {
      name: "Browsing History",
      href: "/#browsing-history",
    },
    {
      name: "Customer Service",
      href: "/page/customer-service",
    },
    {
      name: "About Us",
      href: "/page/about-us",
    },
    {
      name: "Help",
      href: "/page/help",
    },
  ],
  carousels: [
    {
      title: "Latest iPhone 16 Series",
      buttonCaption: "Shop Now",
      image: "/images/banner3.jpg",
      url: "/search?category=Smartphones",
      isPublished: true,
    },
    {
      title: "MacBook Pro with M3 Chip",
      buttonCaption: "Shop Now",
      image: "/images/banner1.jpg",
      url: "/search?category=Laptops",
      isPublished: true,
    },
    {
      title: "iPad Pro - Unleash Your Creativity",
      buttonCaption: "See More",
      image: "/images/banner2.jpg",
      url: "/search?category=Tablets",
      isPublished: true,
    },
  ],
  settings: [
    {
      common: {
        freeShippingMinPrice: 35,
        isMaintenanceMode: false,
        defaultTheme: "Light",
        defaultColor: "Gold",
        pageSize: 9,
      },
      site: {
        name: "ElectroHub",
        description:
          "ElectroHub is your premier destination for the latest electronics, smartphones, laptops, tablets, and tech accessories.",
        keywords: "Electronics, Smartphones, Laptops, Tablets, Apple, Samsung, Oppo, MacBook, iPad, iPhone",
        url: "https://electrohub.vercel.app",
        logo: "/icons/logo.svg",
        slogan: "Power Your Digital Life.",
        author: "ElectroHub",
        copyright: "2000-2024, ElectroHub.com, Inc. or its affiliates",
        email: "admin@electrohub.com",
        address: "1234 Tech Street, Silicon Valley, CA, Zip 12345",
        phone: "+1 (123) 456-7890",
      },
      carousels: [
        {
          title: "Latest iPhone 16 Series",
          buttonCaption: "Shop Now",
          image: "/images/banner3.jpg",
          url: "/search?category=Smartphones",
        },
        {
          title: "MacBook Pro with M3 Chip",
          buttonCaption: "Shop Now",
          image: "/images/banner1.jpg",
          url: "/search?category=Laptops",
        },
        {
          title: "iPad Pro - Unleash Your Creativity",
          buttonCaption: "See More",
          image: "/images/banner2.jpg",
          url: "/search?category=Tablets",
        },
      ],
      availableLanguages: i18n.locales.map((locale) => ({
        code: locale.code,
        name: locale.name,
      })),
      defaultLanguage: "en-US",
      availableCurrencies: [
        {
          name: "United States Dollar",
          code: "USD",
          symbol: "$",
          convertRate: 1,
        },
      ],
      defaultCurrency: "USD",
      availablePaymentMethods: [
        { name: "ABA PayWay", commission: 0 },
        { name: "Cash On Delivery", commission: 0 },
      ],
      defaultPaymentMethod: "ABA PayWay",
      availableDeliveryDates: [
        {
          name: "Tomorrow",
          daysToDeliver: 1,
          shippingPrice: 12.9,
          freeShippingMinPrice: 0,
        },
        {
          name: "Next 3 Days",
          daysToDeliver: 3,
          shippingPrice: 6.9,
          freeShippingMinPrice: 0,
        },
        {
          name: "Next 5 Days",
          daysToDeliver: 5,
          shippingPrice: 4.9,
          freeShippingMinPrice: 35,
        },
      ],
      defaultDeliveryDate: "Next 5 Days",
      // ABA PayWay configuration
      abaPayWay: {
        enabled: false,
        merchantId: "",
        sandboxMode: true,
      },
      // Telegram notification configuration
      telegram: {
        enabled: false,
        botToken: "",
        chatId: "",
        notificationTypes: {
          orderPaid: true,
          orderDelivered: false,
        },
      },
    },
  ],
};

export default data;
